[package]
name = "dummy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "app"
path = "dummy.rs"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
rand = "0.8.4"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
