version: '3.1'

services:
  directory:
    build: ./directory
    image: tp2_directory
    volumes:
      - ./directory/target:/usr/app/target
    environment:
      - PORT=${DIRECTORY_PORT}
      - MAX_NODES=${MAX_NODES}

  alglobo:
    build: ./alglobo
    image: tp2_alglobo_replica
    volumes:
      - ./alglobo/target:/usr/app/target
    environment:
      - PORT=${ALGLOBO_PORT}
      - SLEEP=3
      - DIRECTORY_HOST=directory
      - DIRECTORY_PORT=${DIRECTORY_PORT}
