version: '3.1'

services:
  directory:
    build: ./services/directory
    image: tp2_directory
    env_file:
      - ./config/directory.env
    environment:
      - PORT=${DIRECTORY_PORT}

  alglobo:
    build: ./services/alglobo
    image: tp2_alglobo
    env_file:
      - ./config/alglobo.env
    environment:
      - CONTROL_PORT=${ALGLOBO_CONTROL_PORT}
      - DATA_PORT=${ALGLOBO_DATA_PORT}
      - DIRECTORY_PORT=${DIRECTORY_PORT}
      - SVC_PORT=${SERVICE_PORT}
    volumes:
      - ./.tmp:/usr/app/.tmp
    depends_on:
      - directory
      - airline
      - bank
      - hotel

  airline:
    build: ./services/generic-service
    image: tp2_generic_service
    env_file:
      - ./config/airline.env
    environment:
      - PORT=${SERVICE_PORT}

  bank:
    build: ./services/generic-service
    image: tp2_generic_service
    env_file:
      - ./config/bank.env
    environment:
      - PORT=${SERVICE_PORT}
    volumes:
      - ./.tmp:/usr/app/.tmp

  hotel:
    build: ./services/generic-service
    image: tp2_generic_service
    env_file:
      - ./config/hotel.env
    environment:
      - PORT=${SERVICE_PORT}
