version: '3.1'

services:
    alglobo:
        build: ./alglobo
        image: tp2_alglobo
        env_file:
            - alglobo.env
        stdin_open: true # docker run -i // to retry queries in stdin input
        tty: true # docker run -t
        depends_on:
            - airline
            - bank
            - hotel

    airline:
        build: ./service
        image: tp2_service
        env_file:
            - airline.env

    bank:
        build: ./service
        image: tp2_service
        env_file:
            - bank.env

    hotel:
        build: ./service
        image: tp2_service
        env_file:
            - hotel.env
