version: '3.1'

services:
  alglobo:
    build: ./alglobo
    image: tp2_alglobo
    volumes:
      - /usr/app/target
    env_file:
      - alglobo.env

  airline:
    build: ./service
    image: tp2_service
    volumes:
      - /usr/app/target
    env_file:
      - airline.env

  bank:
    build: ./service
    image: tp2_service
    volumes:
      - /usr/app/target
    env_file:
      - bank.env

  hotel:
    build: ./service
    image: tp2_service
    volumes:
      - /usr/app/target
    env_file:
      - hotel.env
