name: 'TP1 CI'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./TP1
    steps:
      - uses: actions/checkout@v2

      - name: Run check
        run: cargo check --verbose

      - name: Run clippy
        run: cargo clippy --verbose -- -D warnings
