name: 'TP2 CI'

on:
  push:
    paths:
      - TP2/**/*.rs
  pull_request:
    branches:
      - main
    paths:
      - TP2/**/*.rs

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./TP2
    steps:
      - uses: actions/checkout@v2

      - name: Run check
        run: ./check.sh

      - name: Run clippy
        run: ./clippy.sh
