name: 'UI'

on:
  push:
    branches:
      - main
    paths:
      - ui/**/*

jobs:
  deploy:
    needs: []
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Deploy GitHub page
        run: npm run deploy
